### PR TITLE
Adding the Proem framework 0.5.1 pre-alpha

### PR DESCRIPTION
**Pull request by trq**
Ive added the Proem Framework pre-alpha to these benchmarks.

See: https://github.com/proem/proem or http://proemframework.org for more details.

### CODE REVIEW

**Comment by eryx** [comment]
I will merge proem this weekend and give you a simple test results :)

**Comment by trq** [comment]
Hi eryx, thanks. It does require php5.4, which in turn appears to break laravel.

Also, I notice the yaf framework itself doesn't exist (though an app and benchmark for it does). Is there some reason for this?

**Comment by eryx** [comment]
the yaf framework writen in C language and running as a php module, so you must download the source code and make install.  
url:  http://pecl.php.net/package/yaf

**Comment by eryx** [comment]
I have just sent the results to your email (trq#proemframework.org)

**Pull request merged**
